### ISSUE TITLE
No such file or directory: /c/Users/consu_000/.xpacks/ilg/arm-cmsis.git

### ISSUE THREAD

**Issue by carlosdelfino** [micro-os-plus/eclipse-demo-projects#1]
Please, I don´t find nothing about xpack and related it with gcc, cortex-m, stm4 or others.

In the script make reference to a ~/.xpack folder I don´t have this folder and don´t know how I create it.

Windows 10
GIT Bash Shell

My trace form bash:

```
consu_000@SocialSLA MINGW64 ~/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/scripts (script-windows)
$ bash -x generate.sh
+ set -euo pipefail
+ IFS='
        '
+ script=generate.sh
+ [[ generate.sh != /* ]]
++ pwd
+ script=/c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/scripts/generate.sh
++++ dirname /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/scripts/generate.sh
+++ dirname /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/scripts
++ dirname /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus
+ helper_script=/c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/scripts/generate-helper.sh
+ source /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/scripts/generate-helper.sh
++ xpacks_repo_folder=/c/Users/consu_000/.xpacks
+ do_process_args
+ use_development_tree=
+ '[' 0 -gt 0 ']'
+ do_greet
++++ dirname /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/scripts/generate.sh
+++ dirname /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/scripts
++ basename /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus
+ project_name=f4discovery-blinky-micro-os-plus
+ echo '* Generating xpacks for '\''f4discovery-blinky-micro-os-plus'\'' *'
* Generating xpacks for 'f4discovery-blinky-micro-os-plus' *
+ echo

+ do_remove_dest
+++ dirname /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/scripts/generate.sh
++ dirname /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/scripts
+ generated_folder=/c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/generated
+ '[' -d /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/generated ']'
+ echo 'Removing '\''/c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/generated'\''...'
Removing '/c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/generated'...
+ chmod -R +w /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/generated
+ rm -rf /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/generated
+ do_create_dest
+ local file_name=NON_EDITABLE.txt
+ mkdir -p /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/generated
+ echo 'This folder was automatically generated.'
+ echo 'All files are set read-only and cannot be edited.'
+ do_add_arm_cmsis_xpack
+ do_prepare_dest arm-cmsis-xpack
+ echo

+ echo 'Processing '\''arm-cmsis-xpack'\''...'
Processing 'arm-cmsis-xpack'...
+ dest_folder=/c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/generated/arm-cmsis-xpack
+ do_select_pack_folder ilg/arm-cmsis.git ilg/arm/arm-cmsis-xpack
+ '[' -n '' ']'
+ pack_folder=/c/Users/consu_000/.xpacks/ilg/arm-cmsis.git
+ do_create_include
+ echo 'Creating '\''/c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/generated/arm-cmsis-xpack/include'\''...'
Creating '/c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/generated/arm-cmsis-xpack/include'...
+ mkdir -p /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/generated/arm-cmsis-xpack/include
+ cp -r '/c/Users/consu_000/.xpacks/ilg/arm-cmsis.git/CMSIS/Include/*' /c/Users/consu_000/workspace_ARM_Studies/eclipse-demo-projects/f4discovery-blinky-micro-os-plus/generated/arm-cmsis-xpack/include
cp: cannot stat '/c/Users/consu_000/.xpacks/ilg/arm-cmsis.git/CMSIS/Include/*': No such file or directory
```

**Comment by ilg-ul** [comment]
I don't know about Git Bash Shell, but you need to run the `update-xpacks-repo.sh` script first.

on Windows the scripts were tested with MSYS2 and with the new [Windows Subsystem for Linux](update-xpacks-repo.sh).

**Comment by ilg-ul** [comment]
> nothing about xpack

xPacks is the distribution mechanism used by CMSIS++, an extension of CMSIS PACKS.

in addition to https://github.com/micro-os-plus, I have xPacks with third party content at https://github.com/xpacks.

xPacks use [XCDL](http://xcdl.github.io), which is still under development.

**Comment by ilg-ul** [comment]
I updated the main `README.md` to mention `update-xpacks-repo.sh`.

I'll also improve the scripts, to automatically run the script if the `$HOME/.xpacks` folder is not there.

**Comment by carlosdelfino** [comment]
I don´t have the new Window 10, don´t have space in my hardrive for update :(.

About GIT Shell is Fine, work fine. but have crash on msys2 if git shell in path, because it can run bash from git and cygwin.DLL wrong.

I remove all cygwin form my windows, and now use only mgwin and soucery (for make and rm tools) and GitBash

**Comment by ilg-ul** [comment]
>  now use only mgwin and soucery (for make and rm tools)

what advantage do you have over the [Windows Build Tools](http://gnuarmeclipse.github.io/windows-build-tools/)?

> if git shell in path

I strongly recommend NOT to have any such unix tools in PATH. also no arm-none-eabi-gcc, or other cross compiler.

the less weird things (msys, cygwin, minw, git shell, etc) in the system path, the less problems.

similarly I do not install none of MacPorts or Homebrew in my path (and I have many versions installed in parallel).

**Comment by carlosdelfino** [comment]
Windows Build Tool is only  for Windows 10 Anniversary Update - Build 14393
Available as of 08/02/2016.

I for one still can not update my Windows, even it being original, for my HD space limitations.

I've tried to remove a lot of softwares, but I think only formatting again. And I will not do it now.

On the Paths, I always use a BAT file to set the PATHs as conflicting tools, so do not have much problems, except that this was related to the Windows registry.

**Comment by ilg-ul** [comment]
> Windows Build Tool is only for Windows 10

negative. Windows Build Tool is available for all platforms.

Windows Bash for Linux is only for Windows 10. and it requires quite some space to install properly. currently it is beta, with lots of problems to solve, but my scripts ran fine with it. it is a promising technology, to be watched.

**Comment by ilg-ul** [comment]
> I'll also improve the scripts, to automatically run the script if the `$HOME/.xpacks` folder is not there.

done. I guess we can close this ticket.

**Comment by carlosdelfino** [comment]
there was a miscommunication on my part, when I spoke of the "Windows Build Tools" I meant "Bash on Windows" Windows version 10 Bash produced by Canonical and Microsoft partnership.

On the "Windows Build Tools" that you provide, already use too, but I need the other and make the rm tools.

**Comment by ilg-ul** [comment]
> but I need the other

ok, regardless what the other tools are (Cygwin, MSYS2, Git Bash, etc), just be sure they are not in the System or User PATH.

**Comment by carlosdelfino** [comment]
ok.
