### ISSUE TITLE
Semihosting Keyboard Input

### ISSUE THREAD

**Issue by quzhi010** [micro-os-plus/eclipse-demo-projects#8]
Hi,

I'm got the code to compile for my STM32F4 discovery board and it's functioning great! I can see the trace output on my console and it really helps with debugging.

On the other hand, I'm trying to get the other half of the communication channel running which is to send command to the micro by typing in the console. I got a sense that "os_startup_initialize_args" is related to this purpose but couldn't get it to work. Is there any document or example that shows how this can work?

I also tried to use Segger RTT Viewer to do this but it's very slow when I reconfigured the on board ST link debugger to Jlink firmware. It also disconnects too often and is not really usable when debugging.

Thanks for any advice.

Zack

**Comment by ilg-ul** [comment]
I have no experience with semihosting input.

Passing args via semihosting works with J-Link, OpenOCD and QEMU.

For other questions and support please use the https://www.element14.com/community/groups/gnu-arm-eclipse forum.

**Comment by quzhi010** [comment]
Sorry I posted it here. Thanks for the help!
